version: '3.8'
services:
    backend_flask_app:
        container_name: ${TEAM_NAME}_backend_app
        ports:
                - 0.0.0.0:${APP_PORT}:4527
        restart: always
        build:
                context: ./backend
                dockerfile: Dockerfile
                args:
                        DB_NAME: TEAM_1
        depends_on:
                - db
        environment:
                - FLASK_APP=app.py
                - FLASK_RUN_HOST=0.0.0.0
                - FLASK_DEBUG=0
        networks:
                flask_network:
                        aliases:
                                - flask-network
        command: flash run --host=0.0.0.0 --port=5000
    db:
        container_name: ${TEAM_NAME}_db
        image: mariadb:10.5.8
        restart: always
        environment:
                - MYSQL_USER=admin
                - MYSQL_PASSWORD=admin
                - MYSQL_DATABASE=kardashiandb
                - MYSQL_ROOT_PASSWORD=admin
        volumes:
                - flask_volume:/var/lib/mysql
                - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
                - flask_network
volumes:
        flask_volume:
networks:
        flask_network: